import Head from 'next/head'
import Image from 'next/image'
import Product from '../components/Product'
import {useState, useEffect} from 'react'; 
import axios from 'axios'
import { Row, Col } from 'antd';
// import styles from '../styles/Home.module.css'
// import styles from '../styles/global.css'

export default function Home() {
  const [products, setProducts] = useState([]) // создаем пустой массив для дальнейшего обновления
  useEffect(() => {
    const getData = async () => {
      const req = await axios({
        method: "GET",
        url: 'http://localhost:5000/products',
      });
      setProducts(req.data);
    };
    getData();
  }, []);

  const productList = products.map((product) => {
    return (
      <Col className="gutter-row" span={12} key={product.id}>
      <Product
        id={product.id}
        title={product.name}
        img = {product.img}
        price={product.price}
        discount={product.discount}
      />
      </Col>
    );
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline"> Магазин видеокарт </h1>
      <div>
        <Row>
      {productList}
      </Row>
      </div>

    </div>
  )
}
